/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.login.view;

import javax.swing.JOptionPane;

/**
 *
 * @author João Cavalcanti
 */
public class Simulador01View extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public Simulador01View() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonVerificar = new javax.swing.JButton();
        jButtonAvançar01 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxClassificação = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxQuantidade = new javax.swing.JComboBox<>();
        jComboBoxLigação = new javax.swing.JComboBox<>();
        jButtonVoltar2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuLigaçõesCarbono = new javax.swing.JMenu();
        jMenuItemSimulador01 = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemCapa = new javax.swing.JMenuItem();
        jMenuItemLogin = new javax.swing.JMenuItem();
        jMenuItemNovoCadastro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador 01");

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setToolTipText("Capa");
        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(800, 0, 10, 513);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 10, 510);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 503, 810, 10);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 120, 0, 200);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Nível Fácil");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(680, 20, 90, 30);

        jButtonVerificar.setBackground(new java.awt.Color(255, 204, 102));
        jButtonVerificar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonVerificar.setText("Verificar");
        jButtonVerificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButtonVerificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerificarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVerificar);
        jButtonVerificar.setBounds(340, 380, 130, 29);

        jButtonAvançar01.setBackground(new java.awt.Color(255, 204, 102));
        jButtonAvançar01.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAvançar01.setText("Avançar Simulador 02");
        jButtonAvançar01.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButtonAvançar01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAvançar01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvançar01ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAvançar01);
        jButtonAvançar01.setBounds(550, 460, 200, 29);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(500, 370, 0, 120);

        jComboBoxClassificação.setBackground(new java.awt.Color(255, 204, 102));
        jComboBoxClassificação.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBoxClassificação.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxClassificação.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carbono Primário", "Carbono Secundário", "Carbono Terciário", "Carbono Quartenário" }));
        jComboBoxClassificação.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jComboBoxClassificação.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxClassificação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClassificaçãoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxClassificação);
        jComboBoxClassificação.setBounds(540, 320, 210, 35);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Qual é sua classificação");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(280, 250, 340, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantos carbonos a imagem possui? ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(280, 190, 340, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Qual é o tipo de ligação?");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(280, 220, 340, 25);

        jComboBoxQuantidade.setBackground(new java.awt.Color(255, 204, 102));
        jComboBoxQuantidade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBoxQuantidade.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxQuantidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 Carbonos", "4 Carbonos", "14 Carbonos", "Nenhum Carbono" }));
        jComboBoxQuantidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jComboBoxQuantidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxQuantidadeActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxQuantidade);
        jComboBoxQuantidade.setBounds(110, 320, 170, 35);

        jComboBoxLigação.setBackground(new java.awt.Color(255, 204, 102));
        jComboBoxLigação.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBoxLigação.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxLigação.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ligação Simples", "Ligação Dupla", "Ligação Tripla", "Ligação Composta" }));
        jComboBoxLigação.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jComboBoxLigação.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxLigação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLigaçãoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxLigação);
        jComboBoxLigação.setBounds(310, 320, 200, 35);

        jButtonVoltar2.setBackground(new java.awt.Color(255, 204, 102));
        jButtonVoltar2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonVoltar2.setText("Voltar");
        jButtonVoltar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButtonVoltar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltar2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVoltar2);
        jButtonVoltar2.setBounds(430, 460, 100, 29);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Simulador 01");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(250, 10, 320, 64);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\GITHUB\\ws-projetos\\futuratec\\src\\Recursos\\Imagens T.i\\Ligação de Carbono.png")); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(160, 80, 480, 90);

        jMenuBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenuLigaçõesCarbono.setForeground(new java.awt.Color(255, 0, 0));
        jMenuLigaçõesCarbono.setText("Ligações Carbono");
        jMenuLigaçõesCarbono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItemSimulador01.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemSimulador01.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItemSimulador01.setText("Simulador 01");
        jMenuItemSimulador01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuLigaçõesCarbono.add(jMenuItemSimulador01);

        jMenuBar1.add(jMenuLigaçõesCarbono);

        jMenuSair.setText("Sair");
        jMenuSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });

        jMenuItemCapa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemCapa.setText("Capa");
        jMenuItemCapa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemCapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCapaActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemCapa);

        jMenuItemLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_8, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemLogin.setText("Login");
        jMenuItemLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemLogin);

        jMenuItemNovoCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_9, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemNovoCadastro.setText("Novo Cadastro");
        jMenuItemNovoCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemNovoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovoCadastroActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemNovoCadastro);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // TODO add your handling code here:
        CapaVew TelaPrincipal = new CapaVew();
        TelaPrincipal.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuItemNovoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovoCadastroActionPerformed
        // TODO add your handling code here:
        NovoCadastroView TelaPrincipal = new NovoCadastroView();
        TelaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemNovoCadastroActionPerformed

    private void jMenuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginActionPerformed
        // TODO add your handling code here:
        LoginView TelaPrincipal = new LoginView();
        TelaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemLoginActionPerformed

    private void jMenuItemCapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCapaActionPerformed
        // TODO add your handling code here:
        CapaVew TelaPrincipal = new CapaVew();
        TelaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemCapaActionPerformed

    private void jButtonVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerificarActionPerformed
        // TODO add your handling code here:
        
    String respostaComboBox1 = jComboBoxQuantidade.getSelectedItem().toString();
    String respostaComboBox2 = jComboBoxLigação.getSelectedItem().toString();
    String respostaComboBox3 = jComboBoxClassificação.getSelectedItem().toString();
    
    boolean respostaCorreta = verificarRespostas(respostaComboBox1, respostaComboBox2, respostaComboBox3);
    
    if (respostaCorreta) {
        JOptionPane.showMessageDialog(this, "Todas as respostas estão corretas! Avançe para o último.", "Verificação de Respostas", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Alguma(s) resposta(s) está(ão) incorreta(s)!", "Verificação de Respostas", JOptionPane.ERROR_MESSAGE);
    }
    }
    private boolean verificarRespostas(String respostaComboBox1, String respostaComboBox2, String respostaComboBox3) {
    // Lógica de verificação das respostas
    // Compare as respostas selecionadas com as respostas corretas e retorne true se todas estiverem corretas

    // Exemplo de lógica fictícia
    String respostaCorretaComboBox1 = "4 Carbonos";
    String respostaCorretaComboBox2 = "Ligação Simples";
    String respostaCorretaComboBox3 = "Carbono Primário";

    return respostaComboBox1.equals(respostaCorretaComboBox1) &&
           respostaComboBox2.equals(respostaCorretaComboBox2) &&
           respostaComboBox3.equals(respostaCorretaComboBox3);


          
         
      
    }//GEN-LAST:event_jButtonVerificarActionPerformed

    private void jButtonAvançar01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvançar01ActionPerformed
        // TODO add your handling code here:
        
        Simulador02View ApresentaçãoSimulador = new Simulador02View();
        ApresentaçãoSimulador.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAvançar01ActionPerformed

    private void jComboBoxClassificaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClassificaçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClassificaçãoActionPerformed

    private void jComboBoxQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxQuantidadeActionPerformed

    private void jComboBoxLigaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLigaçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLigaçãoActionPerformed

    private void jButtonVoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVoltar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulador01View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulador01View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulador01View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulador01View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulador01View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAvançar01;
    private javax.swing.JButton jButtonVerificar;
    private javax.swing.JButton jButtonVoltar2;
    private javax.swing.JComboBox<String> jComboBoxClassificação;
    private javax.swing.JComboBox<String> jComboBoxLigação;
    private javax.swing.JComboBox<String> jComboBoxQuantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCapa;
    private javax.swing.JMenuItem jMenuItemLogin;
    private javax.swing.JMenuItem jMenuItemNovoCadastro;
    private javax.swing.JMenuItem jMenuItemSimulador01;
    private javax.swing.JMenu jMenuLigaçõesCarbono;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
