/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.login.view;

/**
 *
 * @author João Cavalcanti
 */
public class TelaPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public TelaPrincipalView() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuObjetivoSite = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuLigaçõesCarbono = new javax.swing.JMenu();
        jMenuItemApresentaçãoSimulador = new javax.swing.JMenuItem();
        jMenuItemSimulador01 = new javax.swing.JMenuItem();
        jMenuItemSimulador02 = new javax.swing.JMenuItem();
        jMenuItemSimulador03 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemPatrocinadores = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemCapa = new javax.swing.JMenuItem();
        jMenuItemLogin = new javax.swing.JMenuItem();
        jMenuItemNovoCadastro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setToolTipText("Capa");
        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(800, 0, 10, 513);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 10, 510);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 503, 810, 10);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 120, 0, 200);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quem somos?");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 20, 320, 64);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("dia a dia.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 330, 240, 32);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Olá, bem-vindo a FuturaTec! Um ambiente interativo e educacional;");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 150, 740, 32);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("onde fornecemos a você usuário, informações detalhadas e conceitos");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 180, 750, 32);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("relacionados ao carbono e como suas ligações químicas influenciam");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 210, 740, 32);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Cavalcanti\\Downloads\\Logo Grande.png")); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(170, 420, 460, 80);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("as propriedades dos compostos orgânicos, bem como a importância");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 240, 740, 32);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("dessas ligações para a formação de moléculas complexas encontradas ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 270, 770, 32);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("na natureza e em diversos produtos químicos utilizados no nosso ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 300, 770, 32);

        jMenuBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenuObjetivoSite.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Cavalcanti\\Downloads\\Imagens T.i\\Estrelinha.png")); // NOI18N
        jMenuObjetivoSite.setText("Objetivo do Site");
        jMenuObjetivoSite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuObjetivoSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuObjetivoSiteActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Cavalcanti\\Downloads\\Imagens T.i\\Sair.png")); // NOI18N
        jMenuItem1.setText("Objetivo/Função");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuObjetivoSite.add(jMenuItem1);

        jMenuBar1.add(jMenuObjetivoSite);

        jMenuLigaçõesCarbono.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Cavalcanti\\Downloads\\Imagens T.i\\Ligações Carbono.png")); // NOI18N
        jMenuLigaçõesCarbono.setText("Ligações Carbono");
        jMenuLigaçõesCarbono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItemApresentaçãoSimulador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemApresentaçãoSimulador.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Cavalcanti\\Downloads\\Imagens T.i\\Apresentação Simulador.png")); // NOI18N
        jMenuItemApresentaçãoSimulador.setText("Apresentação Simulador");
        jMenuItemApresentaçãoSimulador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemApresentaçãoSimulador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemApresentaçãoSimuladorActionPerformed(evt);
            }
        });
        jMenuLigaçõesCarbono.add(jMenuItemApresentaçãoSimulador);

        jMenuItemSimulador01.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemSimulador01.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Cavalcanti\\Downloads\\Imagens T.i\\Simulador.png")); // NOI18N
        jMenuItemSimulador01.setText("Simulador 01");
        jMenuItemSimulador01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemSimulador01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSimulador01ActionPerformed(evt);
            }
        });
        jMenuLigaçõesCarbono.add(jMenuItemSimulador01);

        jMenuItemSimulador02.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemSimulador02.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Cavalcanti\\Downloads\\Imagens T.i\\Simulador.png")); // NOI18N
        jMenuItemSimulador02.setText("Simulador 02");
        jMenuItemSimulador02.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemSimulador02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSimulador02ActionPerformed(evt);
            }
        });
        jMenuLigaçõesCarbono.add(jMenuItemSimulador02);

        jMenuItemSimulador03.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemSimulador03.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Cavalcanti\\Downloads\\Imagens T.i\\Simulador.png")); // NOI18N
        jMenuItemSimulador03.setText("Simulador 03");
        jMenuItemSimulador03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemSimulador03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSimulador03ActionPerformed(evt);
            }
        });
        jMenuLigaçõesCarbono.add(jMenuItemSimulador03);

        jMenuBar1.add(jMenuLigaçõesCarbono);

        jMenu3.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Cavalcanti\\Downloads\\Imagens T.i\\Patrocinadores.png")); // NOI18N
        jMenu3.setText("Patrocinadores");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItemPatrocinadores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemPatrocinadores.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Cavalcanti\\Downloads\\Imagens T.i\\Colaboradores.png")); // NOI18N
        jMenuItemPatrocinadores.setText("Patrocinadores");
        jMenuItemPatrocinadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemPatrocinadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPatrocinadoresActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemPatrocinadores);

        jMenuBar1.add(jMenu3);

        jMenuSair.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Cavalcanti\\Downloads\\Imagens T.i\\Sair.png")); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });

        jMenuItemCapa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemCapa.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Cavalcanti\\Downloads\\Imagens T.i\\Capa.png")); // NOI18N
        jMenuItemCapa.setText("Capa");
        jMenuItemCapa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemCapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCapaActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemCapa);

        jMenuItemLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_8, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Cavalcanti\\Downloads\\Imagens T.i\\Login.png")); // NOI18N
        jMenuItemLogin.setText("Login");
        jMenuItemLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemLogin);

        jMenuItemNovoCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_9, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemNovoCadastro.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Cavalcanti\\Downloads\\Imagens T.i\\Novo Cadastro.png")); // NOI18N
        jMenuItemNovoCadastro.setText("Novo Cadastro");
        jMenuItemNovoCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemNovoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovoCadastroActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemNovoCadastro);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCapaActionPerformed
        // TODO add your handling code here:
        CapaVew TelaPrincipal = new CapaVew();
        TelaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemCapaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ObjetivoSiteView TelaPrincipal = new ObjetivoSiteView();
        TelaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemNovoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovoCadastroActionPerformed
        // TODO add your handling code here:
        NovoCadastroView TelaPrincipal = new NovoCadastroView();
        TelaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemNovoCadastroActionPerformed

    private void jMenuObjetivoSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuObjetivoSiteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuObjetivoSiteActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // TODO add your handling code here:
        CapaVew TelaPrincipal = new CapaVew();
        TelaPrincipal.setVisible(true);
        this.setVisible(false);
              
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginActionPerformed
        // TODO add your handling code here:
        LoginView TelaPrincipal = new LoginView();
        TelaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemLoginActionPerformed

    private void jMenuItemPatrocinadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPatrocinadoresActionPerformed
        // TODO add your handling code here:
        PatrocinadoresView TelaPrincipal = new PatrocinadoresView();
        TelaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemPatrocinadoresActionPerformed

    private void jMenuItemSimulador03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSimulador03ActionPerformed
        // TODO add your handling code here:
        Simulador03View ApresentaçãoSimulador = new Simulador03View();
        ApresentaçãoSimulador.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemSimulador03ActionPerformed

    private void jMenuItemApresentaçãoSimuladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemApresentaçãoSimuladorActionPerformed
        // TODO add your handling code here:
        
        ApresentaçãoSimuladorView TelaPrincipal = new ApresentaçãoSimuladorView();
        TelaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemApresentaçãoSimuladorActionPerformed

    private void jMenuItemSimulador01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSimulador01ActionPerformed
        // TODO add your handling code here:
        Simulador01View TelaPrincipal = new Simulador01View();
        TelaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemSimulador01ActionPerformed

    private void jMenuItemSimulador02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSimulador02ActionPerformed
        // TODO add your handling code here:
        Simulador02View ApresentaçãoSimulador = new Simulador02View();
        ApresentaçãoSimulador.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemSimulador02ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemApresentaçãoSimulador;
    private javax.swing.JMenuItem jMenuItemCapa;
    private javax.swing.JMenuItem jMenuItemLogin;
    private javax.swing.JMenuItem jMenuItemNovoCadastro;
    private javax.swing.JMenuItem jMenuItemPatrocinadores;
    private javax.swing.JMenuItem jMenuItemSimulador01;
    private javax.swing.JMenuItem jMenuItemSimulador02;
    private javax.swing.JMenuItem jMenuItemSimulador03;
    private javax.swing.JMenu jMenuLigaçõesCarbono;
    private javax.swing.JMenu jMenuObjetivoSite;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
